
// App inbox
export const APP_INBOX__ON_INIT_ITEMS_LOADING = 'APP_INBOX__ON_INIT_ITEMS_LOADING';
export const APP_INBOX__ON_INIT_ITEMS_RECEIVED = 'APP_INBOX__ON_INIT_ITEMS_RECEIVED';
export const APP_INBOX__ON_INBOX_UPDATE_RECEIVED = 'APP_INBOX__ON_INBOX_UPDATE_RECEIVED';

// App dealbox
export const APP_DEAL_BOX__DEAL_INIT = 'APP_DEAL_BOX__DEAL_INIT';
export const APP_DEAL_BOX__DEAL_CANCELLED = 'APP_DEAL_BOX__DEAL_CANCELLED';

// Post updates
export const POST_VIEW__POST_CHANGED = 'POST_VIEW__POST_CHANGED';
export const POST_VIEW__POST_REMOVED = 'POST_VIEW__POST_REMOVED';
export const POST_VIEW__DEAL_INIT = 'POST_VIEW__DEAL_INIT';
export const POST_VIEW__DEAL_CANCELLED = 'POST_VIEW__DEAL_CANCELLED';

export const POST_STATUS__BIDDING_ADDED = 'POST_STATUS__BIDDING_ADDED';
export const POST_STATUS__BIDDING_CHANGED = 'POST_STATUS__BIDDING_CHANGED';
export const POST_STATUS__BIDDING_REMOVED = 'POST_STATUS__BIDDING_REMOVED';
export const POST_STATUS__DEAL_INIT = 'POST_STATUS__DEAL_INIT';
export const POST_STATUS__DEAL_CANCELLED = 'POST_STATUS__DEAL_CANCELLED';
export const POST_STATUS__ANSWER_ADDED = 'POST_STATUS__ANSWER_ADDED';
export const POST_STATUS__ANSWER_CHANGED = 'POST_STATUS__ANSWER_CHANGED';
export const POST_STATUS__ANSWER_REMOVED = 'POST_STATUS__ANSWER_REMOVED';

// Post stepper
export const POST_STEPPER__DEAL_INIT = 'POST_STEPPER_DEAL_INIT';
export const POST_STEPPER__DEAL_CANCELLED = 'POST_STEPPER_DEAL_CANCELLED';
export const POST_STEPPER__ANSWER_ADDED = 'POST_STEPPER__ANSWER_ADDED';
export const POST_STEPPER__ANSWER_REMOVED = 'POST_STEPPER__ANSWER_REMOVED';

// Post inbox
export const POST_INBOX__ON_INIT_ITEMS_LOADING = 'POST_INBOX__ON_INIT_ITEMS_LOADING';
export const POST_INBOX__ON_INIT_ITEMS_RECEIVED = 'POST_INBOX__ON_INIT_ITEMS_RECEIVED';
export const POST_INBOX__ON_INBOX_UPDATE_RECEIVED = 'POST_INBOX__ON_INBOX_UPDATE_RECEIVED';

// Private chat
export const PRIVATE_CHAT__ON_INIT_MESSAGES_LOADING = 'PRIVATE_CHAT__ON_INIT_MESSAGES_LOADING';
export const PRIVATE_CHAT__ON_INIT_MESSAGES_RECEIVED = 'PRIVATE_CHAT__ON_INIT_MESSAGES_RECEIVED';
export const PRIVATE_CHAT__ON_MESSAGE_RECEIVED = 'PRIVATE_CHAT__ON_MESSAGE_RECEIVED';

export const PRIVATE_CHAT__INIT_IS_READ_RECEIVED = 'PRIVATE_CHAT__INIT_IS_READ_RECEIVED';
export const PRIVATE_CHAT__ON_READ_RECEIVED = 'PRIVATE_CHAT__ON_READ_RECEIVED';

export const PRIVATE_CHAT__INIT_IS_WRITING_RECEIVED = 'PRIVATE_CHAT__INIT_IS_WRITING_RECEIVED';
export const PRIVATE_CHAT__ON_START_TYPING_RECEIVED = 'PRIVATE_CHAT__ON_START_TYPING_RECEIVED';
export const PRIVATE_CHAT__ON_STOP_TYPING_RECEIVED = 'PRIVATE_CHAT__ON_STOP_TYPING_RECEIVED';

// Public chat
export const PUBLIC_CHAT__INIT_MESSAGES_LOADING = 'PUBLIC_CHAT__INIT_MESSAGES_LOADING';
export const PUBLIC_CHAT__ON_INIT_MESSAGES_RECEIVED = 'PUBLIC_CHAT__ON_INIT_MESSAGES_RECEIVED';
export const PUBLIC_CHAT__ON_MESSAGE_RECEIVED = 'PUBLIC_CHAT__ON_MESSAGE_RECEIVED';

export const PUBLIC_CHAT__INIT_CONNECTED_USERS = 'PUBLIC_CHAT__INIT_CONNECTED_USERS';
export const PUBLIC_CHAT__ON_USER_CONNECTED = 'PUBLIC_CHAT__ON_USER_CONNECTED';
