
// App inbox
export const APP_INBOX__ON_INIT_ITEMS_LOADING = 'APP_INBOX__ON_INIT_ITEMS_LOADING';
export const APP_INBOX__ON_INIT_ITEMS_RECEIVED = 'APP_INBOX__ON_INIT_ITEMS_RECEIVED';
export const APP_INBOX__ON_INBOX_UPDATE_RECEIVED = 'APP_INBOX__ON_INBOX_UPDATE_RECEIVED';

// App dealbox
export const APP_DEAL_BOX__DEAL_OPENED = 'APP_DEAL_BOX__DEAL_OPENED';
export const APP_DEAL_BOX__DEAL_CANCELLED = 'APP_DEAL_BOX__DEAL_CANCELLED';

// Post updates
export const POST_UPDATE__POST_CHANGED = 'POST_UPDATE__POST_CHANGED';
export const POST_UPDATE__POST_REMOVED = 'POST_UPDATE__POST_REMOVED';
export const POST_UPDATE__BIDDING_ACCEPTED = 'POST_UPDATE__BIDDING_ACCEPTED';
export const POST_UPDATE__BIDDING_REMOVE_ACCEPTED = 'POST_UPDATE__BIDDING_REMOVE_ACCEPTED';

// Bidding updates
export const BIDDING_UPDATE__BIDDING_ADDED = 'BIDDING_UPDATE__BIDDING_ADDED';
export const BIDDING_UPDATE__BIDDING_CHANGED = 'BIDDING_UPDATE__BIDDING_CHANGED';
export const BIDDING_UPDATE__BIDDING_REMOVED = 'BIDDING_UPDATE__BIDDING_REMOVED';
export const BIDDING_UPDATE__BIDDING_ACCEPTED = 'BIDDING_UPDATE__BIDDING_ACCEPTED';
export const BIDDING_UPDATE__BIDDING_REMOVE_ACCEPTED = 'BIDDING_UPDATE__BIDDING_REMOVE_ACCEPTED';


// Post inbox
export const POST_INBOX__ON_INIT_ITEMS_LOADING = 'POST_INBOX__ON_INIT_ITEMS_LOADING';
export const POST_INBOX__ON_INIT_ITEMS_RECEIVED = 'POST_INBOX__ON_INIT_ITEMS_RECEIVED';
export const POST_INBOX__ON_INBOX_UPDATE_RECEIVED = 'POST_INBOX__ON_INBOX_UPDATE_RECEIVED';

// Private chat
export const PRIVATE_CHAT__ON_INIT_MESSAGES_LOADING = 'PRIVATE_CHAT__ON_INIT_MESSAGES_LOADING';
export const PRIVATE_CHAT__ON_INIT_MESSAGES_RECEIVED = 'PRIVATE_CHAT__ON_INIT_MESSAGES_RECEIVED';
export const PRIVATE_CHAT__ON_MESSAGE_RECEIVED = 'PRIVATE_CHAT__ON_MESSAGE_RECEIVED';

export const PRIVATE_CHAT__INIT_IS_READ_RECEIVED = 'PRIVATE_CHAT__INIT_IS_READ_RECEIVED';
export const PRIVATE_CHAT__ON_READ_RECEIVED = 'PRIVATE_CHAT__ON_READ_RECEIVED';

export const PRIVATE_CHAT__INIT_IS_WRITING_RECEIVED = 'PRIVATE_CHAT__INIT_IS_WRITING_RECEIVED';
export const PRIVATE_CHAT__ON_START_TYPING_RECEIVED = 'PRIVATE_CHAT__ON_START_TYPING_RECEIVED';
export const PRIVATE_CHAT__ON_STOP_TYPING_RECEIVED = 'PRIVATE_CHAT__ON_STOP_TYPING_RECEIVED';

// Public chat
export const PUBLIC_CHAT__INIT_MESSAGES_LOADING = 'PUBLIC_CHAT__INIT_MESSAGES_LOADING';
export const PUBLIC_CHAT__ON_INIT_MESSAGES_RECEIVED = 'PUBLIC_CHAT__ON_INIT_MESSAGES_RECEIVED';
export const PUBLIC_CHAT__ON_MESSAGE_RECEIVED = 'PUBLIC_CHAT__ON_MESSAGE_RECEIVED';

export const PUBLIC_CHAT__INIT_CONNECTED_USERS = 'PUBLIC_CHAT__INIT_CONNECTED_USERS';
export const PUBLIC_CHAT__ON_USER_CONNECTED = 'PUBLIC_CHAT__ON_USER_CONNECTED';
