export enum PostUpdateType {
    POST_CHANGED = 'POST_CHANGED',
    POST_REMOVED = 'POST_REMOVED',

    BIDDING_ADDED = 'BIDDING_ADDED',
    BIDDING_REMOVED = 'BIDDING_REMOVED',
    BIDDING_CHANGED = 'BIDDING_CHANGED',

    DEAL_INIT = 'DEAL_INIT',
    DEAL_CANCELLED = 'DEAL_CANCELLED',

    ANSWER_ADDED = 'ANSWER_ADDED',
    ANSWER_CHANGED = 'ANSWER_CHANGED',
    ANSWER_REMOVED = 'ANSWER_REMOVED'
}
