
export enum UserNotificationType {
    DEAL_INIT_NOTIFICATION = 'DEAL_INIT_NOTIFICATION',
    DEAL_CANCELLED_NOTIFICATION = 'DEAL_CANCELLED_NOTIFICATION',
    POST_NOTIFICATION = 'POST_NOTIFICATION'
}

