
export enum NotificationFeatureType {
    BIDDING_ADDED = 'BIDDING_ADDED',
    BIDDING_CHANGED = 'BIDDING_CHANGED',
    BIDDING_REMOVED = 'BIDDING_REMOVED',

    DEAL_INIT = 'DEAL_INIT',
    DEAL_CANCELLED = 'DEAL_CANCELLED',

    ANSWER_ADDED = 'ANSWER_ADDED',
    ANSWER_CHANGED = 'ANSWER_CHANGED',
    ANSWER_REMOVED = 'ANSWER_REMOVED',
    ANSWER_ACCEPTED = 'ANSWER_ACCEPTED',

    SMART_CONTRACT_PAID = 'SMART_CONTRACT_PAID'
}

