
export enum PostUpdateFeatureType {
    POST_CHANGED = 'POST_CHANGED',
    POST_REMOVED = 'POST_REMOVED',
    BIDDING_ADDED = 'BIDDING_ADDED',
    BIDDING_REMOVED = 'BIDDING_REMOVED',
    BIDDING_CHANGED = 'BIDDING_CHANGED',
    BIDDING_ACCEPTED = 'BIDDING_ACCEPTED'
}
